// liste de prenoms courant issues de insee
// https://www.data.gouv.fr/en/datasets/liste-de-prenoms-et-patronymes

var prenoms = [
'ADRIEN','AGNES','AHMED','AIME','ALAIN','ALBERT','ALEXANDRA','ALEXANDRE','ALEXIS','ALFRED','ALI','ALICE','ALINE','ALPHONSE','ANDRE','ANDREE','ANGELIQUE','ANNA','ANNE','ANNICK','ANNIE','ANTHONY','ANTOINE','ANTOINETTE','ANTONIO','ARLETTE','ARMAND','ARNAUD','AUDREY','AUGUSTE','AURELIE',
'BAPTISTE','BEATRICE','BENJAMIN','BENOIT','BERNADETTE','BERNARD','BERTRAND','BRIGITTE','BRUNO',
'CAMILLE','CAROLE','CAROLINE','CATHERINE','CECILE','CEDRIC','CELINE','CHANTAL','CHARLES','CHARLOTTE','CHRISTELLE','CHRISTIAN','CHRISTIANE','CHRISTINE','CHRISTOPHE','CLAIRE','CLAUDE','CLAUDINE','CLEMENT','COLETTE','CORINNE','CYRIL',
'DAMIEN','DANIEL','DANIELE','DANIELLE','DAVID','DELPHINE','DENIS','DENISE','DIDIER','DOMINIQUE',
'EDMOND','EDOUARD','ELIANE','ELIE','ELISABETH','ELISE','ELODIE','EMILE','EMILIE','EMMANUEL','EMMANUELLE','ERIC','ERNEST','ETIENNE','EUGENE','EVELYNE',
'FABIEN','FABIENNE','FABRICE','FELIX','FERNAND','FLORENCE','FLORENT','FLORIAN','FRANCE','FRANCINE','FRANCIS','FRANCK','FRANCOIS','FRANCOISE','FREDERIC','FREDERIQUE',
'GABRIEL','GABRIELLE','GASTON','GENEVIEVE','GEORGES','GEORGETTE','GERARD','GERMAIN','GERMAINE','GHISLAINE','GILBERT','GILLES','GINETTE','GISELE','GREGORY','GUILLAUME','GUY',
'HELENE','HENRI','HENRIETTE','HERVE','HUBERT','HUGUETTE',
'IRENE','ISABELLE',
'JACKY','JACQUELINE','JACQUES','JANINE','JEAN','JEANINE','JEANNE','JEANNINE','JEREMY','JEROME','JOCELYNE','JOEL','JOELLE','JONATHAN','JOSE','JOSEPH','JOSETTE','JOSIANE','JULES','JULIE','JULIEN','JULIETTE',
'KARINE','KEVIN',
'LAETITIA','LAURA','LAURE','LAURENCE','LAURENT','LEON','LILIANE','LIONEL','LOIC','LOUIS','LOUISE','LUC','LUCIE','LUCIEN','LUCIENNE','LUDOVIC',
'MADELEINE','MAGALI','MANUEL','MARC','MARCEL','MARCELLE','MARGUERITE','MARIA','MARIE','MARINE','MARION','MARIUS','MARTHE','MARTINE','MARYSE','MATHIEU','MATHILDE','MAURICE','MAX','MAXIME','MELANIE','MICHAEL','MICHEL','MICHELE','MICHELINE','MICHELLE','MICKAEL','MIREILLE','MOHAMED','MONIQUE','MURIEL','MYRIAM',
'NADIA','NADINE','NATHALIE','NELLY','NICOLAS','NICOLE','NOEL',
'ODETTE','ODILE','OLIVIER',
'PASCAL','PASCALE','PATRICE','PATRICIA','PATRICK','PAUL','PAULE','PAULETTE','PAULINE','PHILIPPE','PIERRE','PIERRETTE',
'RAPHAEL','RAYMOND','RAYMONDE','REGINE','REGIS','REMI','REMY','RENE','RENEE','RICHARD','ROBERT','ROGER','ROLAND','ROMAIN','ROSE',
'SABINE','SABRINA','SAMUEL','SANDRA','SANDRINE','SARAH','SEBASTIEN','SERGE','SEVERINE','SIMON','SIMONE','SOLANGE','SONIA','SOPHIE','STEPHANE','STEPHANIE','SUZANNE','SYLVAIN','SYLVIE',
'THERESE','THIERRY','THOMAS',
'VALERIE','VANESSA','VERONIQUE','VICTOR','VINCENT','VIRGINIE',
'WILLIAM',
'XAVIER',
'YANN','YANNICK','YVES','YVETTE','YVON','YVONNE'
  ];